server:
  port: 9999
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
      - id: baidu_route
        uri: http://baidu.com:80/
        predicates:
        - Path=/baidu
      discovery:
        locator:
          # 是否与服务发现组件结合，通过serviceId转发到具体的服务实例(默认false)
          enabled: true
          # 表示开启小写的serviceId进行路由转发
          lowerCaseServiceId: true
  #zipkin配置
  zipkin:
    # 未接入Kafka之前的配置
    #ase-url: http://localhost:8240
    sender:
      type: kafka
    kafka:
      topic: zipkin
  kafka:
    bootstrap-servers: http://191.168.56.101:9092
  sleuth:
    Sampler:
      probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://leezy:123456@${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'