server:
  port: 8000
spring:
  application:
    name: spring-cloud-hibernate
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.101:3306/test?characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Zdh!123456
  jpa:
    # 指定数据库类型
    database: mysql
    # 控制台打印SQL
    show-sql: true
    # 建表实时策略，这里用Update，即根据实体更新表结构
    hibernate:
      ddl-auto: update
      # 表中字段命名策略，这里要引入hibernate的核心包，不然这个命名策略会报错
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    # 数据库方言
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect