eureka:
  client:
    serviceUrl:
      defaultZone: http://leezy:123456@${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      user.name: leezy         #These two are needed so that the server
      user.password: 123456 #can access the protected client endpoints
server:
  port: 5000
spring:
  application:
    name: admin-server
  security:
    user:
      name: leezy
      password: 123456
