spring:
  application:
    name: spring-cloud-zipkin-server
server:
  port: 8240
eureka:
  client:
    serviceUrl:
      defaultZone: http://leezy:123456@${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
zipkin:
  collector:
    kafka:
      bootstrap-servers: http://192.168.56.101:9092
      zookeeper: http://192.168.56.101:2181
      topic: zipkin
management:
  metrics:
    web:
      server:
        auto-time-requests: false