server:
  port: 8101
spring:
  application:
    name: spring-cloud-mybatis
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.101:3306/test?characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Zdh!123456
  # Redis相关配置
  redis:
    host: 192.168.56.101
    port: 6379
    password: root
    # Redis默认采用一主三从的配置方式来提高缓存的吞吐量
    # cluster:
      # nodes: ip:port,ip:port,ip:port
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
    timeout: 20000
mybatis:
  # 声明Mapper的地址
  mapper-locations: classpath*:org/spring/cloud/service/UserMapper.xml
  # 声明实体类的位置
  type-aliases-package: org.spring.cloud.po
logging:
  level:
    root: DEBUG