server:
  port: 9099
eureka:
  client:
    serviceUrl:
      defaultZone: http://leezy:123456@${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
# 开启Feign对Hystrix的支持
feign:
  hystrix:
    enabled: true
ribbon:
  # 请求处理的超时时间
  ConnectTimeout: 6000
  # 请求连接的超时时间
  ReadTimeout: 6000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# Hystrix的超时时间设置
hystrix:
  command:
    default:
      execution:
        timeout:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
spring:
  zipkin:
    base-url: http://localhost:8240
  sleuth:
    sampler:
      probability: 1.0